/**
 * Formats a single grammar symbol for LaTeX, handling epsilons and subscripts.
 * e.g., 'ε' -> '\epsilon', 'X1' -> 'X_{1}', 'S0' -> 'S_{0}'
 */
const formatSymbol = (sym) => {
  if (sym === 'ε') return '\\epsilon';
  // Match a capital letter followed by one or more digits
  if (/^[A-Z]\d+$/.test(sym)) {
    return `${sym[0]}_{${sym.slice(1)}}`;
  }
  return sym;
};

/**
 * Converts a grammar structure into a formatted LaTeX equation block.
 * @param {Object} grammar - The grammar object, e.g., { "S": [["A", "B"], ["a"]] }
 * @returns {string} Formatted LaTeX string
 */
export function grammarToLatex(grammar) {
  if (!grammar || Object.keys(grammar).length === 0) {
    return "% Empty grammar\n";
  }

  let latex = "% Add \\usepackage{amsmath} to your LaTeX preamble!\n\\begin{align*}\n";

  const entries = Object.entries(grammar);
  
  entries.forEach(([head, productions], index) => {
    const latexHead = formatSymbol(head);

    const formattedProductions = productions.map(prod => {
      if (!prod || prod.length === 0 || (prod.length === 1 && prod[0] === 'ε')) {
        return '\\epsilon';
      }
      return prod.map(symbol => formatSymbol(symbol)).join(' ');
    });

    const rhs = formattedProductions.join(' \\mid ');
    
    latex += `  ${latexHead} &\\rightarrow ${rhs}`;
    
    if (index < entries.length - 1) {
      latex += " \\\\\n";
    } else {
      latex += "\n";
    }
  });

  latex += "\\end{align*}";
  return latex;
}

/**
 * Converts a parse tree generated by CYK into a tikz-qtree LaTeX string.
 * @param {Object} tree - The root node of the parse tree
 * @returns {string} Formatted tikz-qtree LaTeX string
 */
export function parseTreeToLatex(tree) {
  if (!tree) return "";

  const traverse = (node) => {
    if (!node) return "";
    
    // Process symbol using the formatSymbol logic we built for the alignment block
    let formattedSym = formatSymbol(node.sym);
    
    // Terminals like 'a' are printed normally, but variables/epsilons are wrapped in math mode ($...$)
    let label = node.terminal && formattedSym !== '\\epsilon' ? formattedSym : `$${formattedSym}$`;

    if (!node.children || node.children.length === 0) {
      // Leaf node
      return label;
    }
    
    const childrenStr = node.children.map(child => traverse(child)).join(' ');
    
    return `[.{${label}} ${childrenStr} ]`;
  };

  return `% Add \\usepackage{tikz-qtree} to your LaTeX preamble\n\\Tree ${traverse(tree)}`;
}
